@startuml King Of Figther a mi estilo

class Personaje{
    + Carga
    + Vida
    + Energia
}
class Partida
class Ronda
class Temporizador
class EstadoJuego
class Jugador{
    + Jugador1
    + Jugador2
}
class JugadorHumano
class JugadorCPU
class Equipo
class ControlEntrada{
    - palanca
    - botonA
    - botonB
    - botonC
    - botonD
    + moverIzquierda()
    + moverDerecha()
    + moverArriba()
    + moverAbajo()
    + presionarBotonA()
    + presionarBotonB()
    + presionarBotonC()
    + presionarBotonD()
}
class SeleccionPersonaje
class Personaje
class EstadisticasPersonaje
class EstadoPersonaje
class AnimacionPersonaje
class Habilidad
class PatadaFuerte
class PatadaLeve
class GolpeFuerte
class GolpeLeve
class SistemaCombate
class SistemaColisiones
class ObjetoGolpe
class ObjetoDaño
class SistemaDaño
class SistemaCombo
class Escenario
class Fondo
class ObjetoEscenario


Jugador *-- ControlEntrada
Personaje *-- EstadisticasPersonaje
Personaje *-- EstadoPersonaje
Personaje *-- AnimacionPersonaje
Personaje *-- Habilidad
PatadaFuerte --|> Habilidad
PatadaLeve --|> Habilidad
GolpeFuerte --|> Habilidad
GolpeLeve --|> Habilidad
SistemaCombate *-- SistemaColisiones
SistemaCombate *-- SistemaDaño
SistemaCombate *-- SistemaCombo
SistemaColisiones *-- ObjetoGolpe
SistemaColisiones *-- ObjetoDaño
Personaje *-- SistemaCombate

Partida "1" *-- "1..2" Jugador
Jugador "1" *-- "3" Personaje
Partida "1" *-- "1..6" Ronda
Personaje "0" *-- "5" Energia
Personaje "0" *-- "100" Vida
Temporizador "0" *-- "60" Segundos
